### PR TITLE
ADD supported_list public getter

### PR DESCRIPTION
**Pull request by MiquelIR**
New getter function to receive the list of all the PRIME codes of the supported reports.

The property that existed to do that required an already built Report object to call it. This one doesn't because is an static method

### CODE REVIEW

**Comment by ecarreras** [comment]
I don't understand why you need this, you can do:

```python
from primestg.report.reports import SUPPORTED_REPORTS
```

And get the list

**Comment by ecarreras** [comment]
If you want you can make a module method like `is_supported()` and then this method check if the parameters is in the supported reports list.

**Comment by MiquelIR** [comment]
I changed it for the method you said. But you're right I could just import the list

**Comment by ecarreras** [comment]
> I changed it for the method you said. But you're right I could just import the list

Cool @MiquelIR , now you can change the code in https://github.com/gisce/primestg/blob/5c101dc98dd79635421fdbe12b2f60f63c6e715f/primestg/report/reports.py#L1237

To use this method, if in the future we change some behavior all will remain in this method

**Pull request merged**
