### PR TITLE
ADD code to read S24 report

### PR DESCRIPTION
**Pull request by MiquelIR**
Add necessary methos to support the S24 report on the library

### CODE REVIEW

**Comment by MiquelIR** [comment]
Output sample from a S24 read:
```
[{'meters': [{'active': True,
    'name': 'CIR0501407341',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:59'},
   {'active': True,
    'name': 'CIR0501701201',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:51'},
   {'active': True,
    'name': 'CIR0501701209',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:47'},
   {'active': True,
    'name': 'CIR0501701426',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:35'},
   {'active': True,
    'name': 'CIR0501701428',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:02:03'},
   {'active': True,
    'name': 'CIR2081707282',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 01:10:25'},
   {'active': True,
    'name': 'SAG0165790033',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:39'},
   {'active': True,
    'name': 'SAG0165790092',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:55'},
   {'active': True,
    'name': 'SAG0165790094',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:43'},
   {'active': True,
    'name': 'SAG0175811896',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:01:41'},
   {'active': True,
    'name': 'SAG0176451405',
    'season': 'S',
    'status': 2,
    'timestamp': '2018-05-29 09:02:07'}],
  'season': 'S',
  'timestamp': '2018-05-29 09:02:34'}]

**Comment by ecarreras** [comment]
Don't forget the tests! :100:

**Comment by MiquelIR** [comment]
@ecarreras Don't merge this yet! I will try to add the Concentrator name to the result object.

**Comment by MiquelIR** [comment]
OKey! It's ready now!

**Pull request merged**
