### PR TITLE
SOAP service structure

### PR DESCRIPTION
**Pull request by MiquelIR**
- [x] Add first functional structure of the SOAP service

### CODE REVIEW

**Comment by ecarreras** [comment]
Necessitem tests per això ;-)

https://github.com/getsentry/responses

**Comment by MiquelIR** [comment]
Right now test fail because i haven't upload the real URI's to the services and so on.

**Comment by MiquelIR** [comment]
[Testing del Web service de PrimeSTG](https://trello.com/c/OTHAmNAO/15-testing-del-web-service-de-primestg)

**Comment by MiquelIR** [comment]
[Use travis encryption to encrypt the WSDL file.](https://trello.com/c/dqWCYflA/17-use-travis-encryption-to-encrypt-the-wsdl-file)

**Comment by MiquelIR** [comment]
working with : https://github.com/gisce/openstg/pull/3

**Pull request merged**
